import csv
import os
import random
from collections import defaultdict

# Configuration
file_path = 'Results_Skewness.csv'
output_tex = 'Plot_Skewness.tex'

# Color palette (matching the Python/matplotlib version)
custom_palette = {
    'GC':  'e31a1c',   # Red
    'MDL': '1a1de6',   # Blue
    'DT':  'D4A017',   # Darker yellow for better visibility on white
    'MLP': '33a02c',   # Green
}

# Marker map (pgfplots marker names)
marker_map = {
    'GC':  '*',           # filled circle
    'MDL': '*',           # filled circle
    'DT':  'triangle*',   # filled triangle
    'MLP': 'square*',     # filled square
}

# Marker sizes
scatter_mark_size = {
    'GC': '1.6pt', 'MDL': '1.6pt', 'DT': '2pt', 'MLP': '1.6pt',
}
mean_mark_size = {
    'GC': '2.5pt', 'MDL': '2.5pt', 'DT': '3pt', 'MLP': '2.5pt',
}

# Scenarios: (type_name, methods_to_plot)
scenarios = [
    ('Partial', ['GC', 'DT', 'MLP']),
    ('Noise',   ['MDL', 'DT', 'MLP']),
]

JITTER_SEED = 42
JITTER_RANGE = 0.02   # ±0.02 in alpha units
SCATTER_OPACITY = 0.35


def read_csv(path):
    """Read CSV and return list of dicts with partialed alpha."""
    with open(path, newline='') as f:
        reader = csv.DictReader(f)
        rows = list(reader)
    for r in rows:
        r['alpha'] = float(r['alpha'].rstrip('.'))
        r['f1'] = float(r['f1'])
    return rows


def compute_mean_f1(rows, scenario_type, methods):
    """Return {method: [(alpha, mean_f1), ...]} sorted by alpha."""
    groups = defaultdict(list)
    for r in rows:
        if r['type'] == scenario_type and r['method'] in methods:
            groups[(r['method'], r['alpha'])].append(r['f1'])

    result = {}
    for m in methods:
        alphas = sorted({k[1] for k in groups if k[0] == m})
        result[m] = [(a, sum(groups[(m, a)]) / len(groups[(m, a)])) for a in alphas]
    return result


def collect_scatter(rows, scenario_type, methods, rng):
    """Return {method: [(jittered_alpha, f1), ...]}."""
    result = {m: [] for m in methods}
    for r in rows:
        if r['type'] == scenario_type and r['method'] in methods:
            jitter = rng.uniform(-JITTER_RANGE, JITTER_RANGE)
            result[r['method']].append((r['alpha'] + jitter, r['f1']))
    return result


def format_coords(points, precision=4):
    """Format a list of (x, y) pairs as pgfplots coordinates string."""
    parts = []
    for x, y in points:
        parts.append(f'({x:.{precision}f},{y:.{precision}f})')
    # Wrap every 5 points for readability
    lines = []
    for i in range(0, len(parts), 5):
        lines.append(' '.join(parts[i:i+5]))
    return '\n'.join(lines)


def generate_tex(rows):
    """Build the full TeX string."""
    rng = random.Random(JITTER_SEED)

    lines = []
    lines.append(r'% Auto-generated by visual_skewness_tikzpicture.py')
    lines.append(r'% Input : ' + file_path)
    lines.append(r'% Output: ' + output_tex)
    lines.append(r'')
    lines.append(r'\documentclass[border=5pt]{standalone}')
    lines.append(r'\usepackage{pgfplots}')
    lines.append(r'\pgfplotsset{compat=1.18}')
    lines.append(r'')

    # ── colour definitions ──
    for method, hexcol in custom_palette.items():
        lines.append(rf'\definecolor{{col{method}}}{{HTML}}{{{hexcol}}}')
    lines.append(r'')

    # ── reusable axis style ──
    lines.append(r'\pgfplotsset{')
    lines.append(r'  skewaxis/.style={')
    lines.append(r'    width=14cm, height=7.5cm,')
    lines.append(r'    xlabel={Dirichlet Alpha ($\alpha$)},')
    lines.append(r'    ylabel={F1 Score},')
    lines.append(r'    xmin=0.0, xmax=1.0,')
    lines.append(r'    ymin=0.35, ymax=1.05,')
    lines.append(r'    ytick={0.4,0.5,0.6,0.7,0.8,0.9,1.0},')
    lines.append(r'    xtick={0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9},')
    lines.append(r'    grid=major,')
    lines.append(r'    grid style={gray!30},')
    lines.append(r'    legend style={')
    lines.append(r'      at={(0.02,0.02)}, anchor=south west,')
    lines.append(r'      font=\small, draw=gray!60,')
    lines.append(r'      fill=white, fill opacity=0.9, text opacity=1,')
    lines.append(r'      rounded corners=2pt,')
    lines.append(r'    },')
    lines.append(r'    title style={font=\large\bfseries, yshift=4pt},')
    lines.append(r'    label style={font=\small},')
    lines.append(r'    tick label style={font=\footnotesize},')
    lines.append(r'    every axis plot/.append style={thick},')
    lines.append(r'  },')
    lines.append(r'}')
    lines.append(r'')

    # ── document body ──
    lines.append(r'\begin{document}')
    lines.append(r'\begin{tikzpicture}')
    lines.append(r'')

    y_offsets = [('8cm', 'partial'), ('0cm', 'noise')]  # top / bottom

    for idx, (scenario_type, methods) in enumerate(scenarios):
        y_off, axis_name = y_offsets[idx]

        mean_data  = compute_mean_f1(rows, scenario_type, methods)
        scatter_data = collect_scatter(rows, scenario_type, methods, rng)

        lines.append(f'% {"=" * 50}')
        lines.append(f'%  {scenario_type}')
        lines.append(f'% {"=" * 50}')
        lines.append(r'\begin{axis}[')
        lines.append(r'  skewaxis,')
        lines.append(f'  title={{{scenario_type}}},')
        lines.append(f'  name={axis_name},')
        lines.append(f'  at={{(0,{y_off})}},')
        lines.append(r']')
        lines.append(r'')

        # ── Scatter plots (individual runs, semi-transparent) ──
        for m in methods:
            lines.append(f'% {m} scatter (individual runs)')
            lines.append(
                rf'\addplot[only marks, mark={marker_map[m]}, '
                rf'mark size={scatter_mark_size[m]}, '
                rf'col{m}, opacity={SCATTER_OPACITY}] coordinates {{')
            lines.append(format_coords(scatter_data[m]))
            lines.append(r'};')
            lines.append(r'')

        # ── Mean-line plots ──
        for m in methods:
            lines.append(f'% {m} mean line')
            lines.append(
                rf'\addplot[col{m}, mark={marker_map[m]}, '
                rf'mark size={mean_mark_size[m]}, '
                rf'line width=1.2pt] coordinates {{')
            lines.append(format_coords(mean_data[m]))
            lines.append(r'};')
            lines.append(rf'\addlegendentry{{{m} (Mean)}}')
            lines.append(r'')

        # ── Annotation box ──
        lines.append(r'% Annotation')
        lines.append(
            r'\node[anchor=south east, font=\scriptsize, text=gray!70!black,'
        )
        lines.append(
            r'      fill=white, fill opacity=0.85, text opacity=1,'
        )
        lines.append(
            r'      draw=gray!40, rounded corners=2pt, inner sep=3pt]'
        )
        lines.append(r'  at (rel axis cs:0.98,0.02)')
        lines.append(
            r'  {\begin{tabular}{@{}l@{}}Scatter: individual runs\\'
            r'Lines: Mean F1\end{tabular}};'
        )
        lines.append(r'')
        lines.append(r'\end{axis}')
        lines.append(r'')

    lines.append(r'')
    lines.append(r'\end{tikzpicture}')
    lines.append(r'\end{document}')

    return '\n'.join(lines)


def main():
    if not os.path.exists(file_path):
        print(f'Error: {file_path} not found in the current directory.')
        return

    rows = read_csv(file_path)
    tex_content = generate_tex(rows)

    with open(output_tex, 'w') as f:
        f.write(tex_content)

    print(f'TikZ visualization saved to: {output_tex}')


if __name__ == '__main__':
    main()
